### ISSUE TITLE
MAX_CONNS not being respected

### ISSUE THREAD

**Issue by dnp1** [jneight/django-db-geventpool#45] opened 2020-03-12 21:28 UTC
Hello, I'm make some experimentations running django 3 under gevent.

I've created an endpoint that execute a `pg_sleep` faking slow queries, then, I used vegeta for tests my setup with high load. 

my MAX_CONNS was 10.

But some of my api response was 500 :
```
Traceback (most recent call last):
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/danilo/Code/django_db__pool_issues_example/app/sleep_db.py", line 9, in sleep_in_db
    with connection.cursor() as cursor:
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django/db/backends/base/base.py", line 260, in cursor
    return self._cursor()
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django/db/backends/base/base.py", line 236, in _cursor
    self.ensure_connection()
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django/db/backends/base/base.py", line 197, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django_db_geventpool/backends/postgresql_psycopg2/base.py", line 49, in get_new_connection
    self.connection = self.pool.get()
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django_db_geventpool/backends/postgresql_psycopg2/psycopg2_pool.py", line 48, in get
    conn = self.create_connection()
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django_db_geventpool/backends/postgresql_psycopg2/psycopg2_pool.py", line 84, in create_connection
    conn = self.connect(*self.args, **self.kwargs)
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/psycogreen/gevent.py", line 32, in gevent_wait_callback
    state = conn.poll()
django.db.utils.OperationalError: FATAL:  sorry, too many clients already
```

I've uploaded a project to show it.
https://github.com/dnp1/django_db_gevent_pool_issues_example

My attack was:
echo "GET http://localhost:8000/sleep_in_db" | vegeta attack -duration=10s --rate 100 | tee results.bin | vegeta report

When I watched the database:
`SELECT * FROM "pg_stat_activity" WHERE "client_addr" = '172.26.0.1'` there was 99 connections of my application.

I'm using python 3.6.10 (CPython) under Linux.
My postgres is running inside a docker container

**Comment by jneight** [comment] 2020-03-26 17:43
Hi, thanks for reporting this issue!

 I was able to reproduce the problem, if I'm not wrong the issue is related with this line https://github.com/jneight/django-db-geventpool/blob/master/django_db_geventpool/backends/postgresql_psycopg2/psycopg2_pool.py#L39, your attack is able to empty the queue so the get_nowait() raises an exception and a new connection is opened here https://github.com/jneight/django-db-geventpool/blame/35585d881f7f0cea1981a8e453e50017fb333332/django_db_geventpool/backends/postgresql_psycopg2/psycopg2_pool.py#L48.

Finally, when the connection is closed, in case the queue is full, the connection is closed and discarded, see https://github.com/jneight/django-db-geventpool/blame/35585d881f7f0cea1981a8e453e50017fb333332/django_db_geventpool/backends/postgresql_psycopg2/psycopg2_pool.py#L56

The fix should be to just wait calling [get()](https://docs.python.org/3.8/library/queue.html#queue.Queue.get)

**Comment by joekohlsdorf** [comment] 2020-04-25 06:07
This change was introduced in https://github.com/jneight/django-db-geventpool/pull/38.
According to the author of the PR this is the desired behavior.

**Comment by bellini666** [comment] 2020-05-08 15:39
I just created a PR to solve this problem by adding a new option to really make MAX_CONNS be respected while keeping the default option as the previous behaviour.

**Comment by joekohlsdorf** [comment] 2020-05-15 02:31
@dnp1 Can you test with 3.1.0, I just did some tests and it also seems to happen with that version.

Not sure what is causing it yet, I am 100% sure that it worked fine before with 3.1.0 but meanwhile in my environment we changed almost everything related to this like Python, Django, gunicorn, gevent and psycopg versions.

**Comment by bellini666** [comment] 2020-05-15 12:45
@joekohlsdorf from what I can tell, the previous version had a small issue here: https://github.com/jneight/django-db-geventpool/blob/a53a258eec27f76939516792020192c565d6f8ee/django_db_geventpool/backends/postgresql_psycopg2/psycopg2_pool.py#L48

As you can see, when that new_connection was used, it would create a new connection without doing `self.size += 1`. That could probably lead to more connections being used.

Either way, I don't know if you saw my update to my PR, but I changed it a lot based on your comment and we are waiting for your feedback so it can get merged. In it I already fixed that issue you are mentioning by making sure that all new connections will increase `self.size`

**Closed** 2020-07-06 09:23 UTC

**Comment by s4ke** [comment] 2020-07-23 15:20
Thanks for the fix @bellini666 . Just had an issue with a lot of extra connections being created and this fixed it.
